[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "bga_filter_worker"
version = "0.1.0"

authors = [
    { name = "Tom Scott", email = "tscott@stratanetworks.com" }
]

requires-python = ">= 3.10"

dependencies = [
    "faust-streaming[fast]>=0.11.3",
]

[tool.hatch.build.hooks.polylith-bricks]

[tool.polylith.bricks]
"../../bases/bce/bga_filter_worker" = "bce/bga_filter_worker"

"../../components/bce/kafka_raw_logs_filter" = "bce/kafka_raw_logs_filter"
