python_sources(
    name="adapters",
    dependencies=[
        "3rd-party/python:reqs",
        "src/python/playground/bridge_agent/domain:domain",
        "src/python/playground/bridge_agent/ports:ports",
    ],
)
